### ISSUE TITLE
Word wrap does not honour font size

### ISSUE THREAD

**Issue by cpressey** [XelaRellum/ZPlet#2]
Maybe I'm doing something wrong, but the word-wrap logic seems to assume the font size is always the default font size (which is 12.)

See attached screenshot.  The top applet has FontSize 12, the middle applet FontSize 16, and the bottom applet FontSize 8.  All three applets have width 480, although the problem manifests no matter what the width of the applet is.

I may or may not be able to find the time to take a shot at fixing it myself.  I'll update this issue with a PR if I do.

![zplet_screenshot](https://cloud.githubusercontent.com/assets/6860877/5790196/372f18c2-9e85-11e4-95f1-12c020321e6b.png)

**Comment by XelaRellum** [comment]
Thanks for the pull request.
